const sets = [];

sets.push([
  [
    `Why not make a movie called <%TITLE%>`,
    `Let's make a movie called <%TITLE%>`,
    `<%TITLE%> is a great name for a movie.`,
    `<%TITLE%> I'd love to see that!`,
    `Can you believe there isn't a movie called <%TITLE%>`,
    `<%TITLE%> Box. Office. Gold.`,
    `Here's an idea for a movie: <%TITLE%>`,
    `<%TITLE%> It practically writes itself.`,
    `Fire up Kickstarter and let's fund the shit out of <%TITLE%>`,
    `I got a script here for <%TITLE%>`,
    `More romantic than Gone With The Wind, it's <%TITLE%>`,
    `Scarier than Psycho. I'm talking about <%TITLE%>`,
    `More excellent than Bill and Ted's adventure. It's <%TITLE%>`,
    `Trippier than 2001: A Space Odyssey. We're making <%TITLE%>`,
    `I'm thinking about a movie called <%TITLE%>`,
    `Let's make <%TITLE%>`,
  ],
]);

sets.push([
  [
    `Let's`,
    `Gonna`,
    `I wanna`,
    `We should`,
    `I'd love to`,
    'Time to',
    `You should`,
    `Why not`,
    `We're totally gonna`,
    `You'll regret it for the rest of your life if you don't`,
    `Somebody ought to`,
    `The plan is to`,
    `The world wants us to`,
    `Get ready to`,
    `The world won't know what hit it when we`,
  ],
  [
    ` cook up`,
    ` make`,
    ` release`,
    ` cut a trailer for`,
    ` start filming`,
    ` crank out`,
    ` hire a crew for`,
    ` get some money to make`,
    ` smash the system with`,
    ` shock the establishment with`,
    ` offend some old people with`,
    ` make some serious coin out of`,
    ` break box office records with`,
    ` shake things up with`,
    ` freak out Hollywood with`,
    ` get all hipster and indy with`,
    ` sell out to the masses with`,
    ` re-invent the rom-com with`,
    ` turn horror upside down with`,
    ` make 'em laugh with`,
    ` gross out the Sundance crowd with`,
    ` rule SXSW with`,
    ` get Mark Zuckerberg to finance`,
  ],
  [' <%TITLE%>'],
]);

module.exports = sets;
